<?php

/**
 * PluginAlbumImageCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAlbumImageCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAlbumImageCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAlbumImageComment');
    }
}