<?php

/**
 * PluginAlbumCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAlbumCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAlbumCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAlbumComment');
    }
}