<?php

/**
 * PluginAlbumLikeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAlbumLikeTable extends Doctrine_Table
{
    public function getAlbumLike($albumId, $memberId)
    {
      $q = $this->createQuery()
        ->where('album_id = ?', $albumId)
        ->andWhere('member_id = ?', $memberId);
        
      return $q->fetchOne();
    }
}