<?php

/**
 * PluginAlbumImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5925 2009-06-22 21:27:17Z jwage $
 */
abstract class PluginAlbumImage extends BaseAlbumImage
{
  public function save(Doctrine_Connection $conn = null)
  {
    $this->setFileNamePrefix();

    return parent::save($conn);
  }

  protected function setFileNamePrefix()
  {
    $prefix = 'A_'.$this->getAlbum()->getId().'_'.$this->getAlbum_id().'_';
    $file = $this->getFile();
    $file->setName($prefix.$file->getName());
  }
}
