<?php

/**
 * PluginAlbumImageComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginAlbumImageComment extends BaseAlbumImageComment
{
  public function isDeletable($memberId)
  {
    return $this->member_id === $memberId || $this->AlbumImage->isAuthor($memberId);
  }
}